services:
  cert-manager:
    global_permissions:
    - '* certmanager.k8s.io/*'
    - '* extensions/ingresses'
    - '* configmaps'
    - '* secrets'
    - '* events'
    - '* services'
    - '* pods'
    image: ${CERT_MANAGER_IMAGE}
    imagePullPolicy: Always
    command:
    - cert-manager
    - --leader-election-namespace
    - rio-system
    - --cluster-resource-namespace
    - rio-system
    - --logtostderr
    - "true"

questions:
- variable: CERT_MANAGER_IMAGE
  description: "cert manager image to use"

