services:
  cert-manager:
    disableServiceMesh: true
    global_permissions:
    - '* certmanager.k8s.io/*'
    - '* extensions/ingresses'
    - '* configmaps'
    - '* secrets'
    - '* events'
    - '* services'
    - '* pods'
    image: rancher/cert-manager-controller:v0.7.2-rio.1
    imagePullPolicy: Always
    args:
    - cert-manager
    - --leader-election-namespace
    - ${NAMESPACE}
    - --cluster-resource-namespace
    - ${NAMESPACE}
    - --logtostderr
    - "true"

